services:
  - type: web
    name: sistema-pedidos-restaurante
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: https://jfvkhoxhiudtxskylnrv.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmdmtob3hoaXVkdHhza3lsbnJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTQ0MjYsImV4cCI6MjA3MTc5MDQyNn0.S4Xq8j1e6WRDYX-MKTFq1jCDobz1JIDkLn_6-GH-ejc
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmdmtob3hoaXVkdHhza3lsbnJ2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjIxNDQyNiwiZXhwIjoyMDcxNzkwNDI2fQ.Cxb0AYJnOwwWhtxeunUeM0oA5cmqNWXOPSlmbBQpYnE
      - key: JWT_SECRET
        value: YPGCjPXNmbNaFYVOvtznVqkmejwAFg+L/Y22fFNdy4JcqyBm0rzP3U/TrYnrT0THQeiWzB+Nw16AgD1PhEhriA==
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: CORS_ORIGIN
        value: https://vermillion-snickerdoodle-5f1291.netlify.app
      - key: FRONTEND_URL
        value: https://vermillion-snickerdoodle-5f1291.netlify.app
