services:
  - type: web
    name: sistema-pedidos-backend
    env: node
    plan: free
    region: oregon
    branch: main
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # PORT se inyecta automáticamente por Render - NO definir aquí
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: CORS_ORIGIN
        value: https://sistema-pedidos-kurp.netlify.app
      - key: FRONTEND_URL
        value: https://sistema-pedidos-kurp.netlify.app


